### ISSUE TITLE
Catalyst live site checklist

### ISSUE THREAD

**Issue by evan10s** [HackGT/live-site-old#48]
- [x] Add event-specific styling
- [x] Add a favicon
- [ ] Add app icons (in `/assets`)
- [x] Add content to the home page
- [x] If your event has a map, add a page for it (you might want to [add an image](https://github.com/HackGT/live-site/wiki/Creating-Generic-Pages#adding-images) as well)
- [x] Create and add content for any other custom pages you want
- [x] Add or update the custom navbar links (see `_data/navbar_links.yaml`)
- [x] Link to your social media in the footer (see `_data/social_media.yaml`)
- [x] Create OneSignal integration and update `oneSignalAppId` in `_config.yml`
- [x] Setup Google Calendar(s) for your event schedule(s) and add your API key and calendar ID(s) (@kexin-zhang)
- [x] If you want to use the feedback form (appears in the footer), set the `url`, `form_id`, and `feedback` variables in `_config.yml`
- [x] Deploy the site (if HackGT, in Biodomes)
- [x] Update `manifest.json`
